// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using weightech_api.Models;

#nullable disable

namespace weightech_api.Migrations
{
    [DbContext(typeof(afnlContext))]
    [Migration("20250731203002_removeIdAndserverIndex")]
    partial class removeIdAndserverIndex
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.2");

            modelBuilder.Entity("weightech_api.Models.CaseweigherTableModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("High_limit")
                        .HasColumnType("REAL");

                    b.Property<double>("Low_limit")
                        .HasColumnType("REAL");

                    b.Property<double>("Net_lb")
                        .HasColumnType("REAL");

                    b.Property<long>("Serial")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Timestamp" }, "IX_caseweigher_timestamp");

                    b.ToTable("caseweigher", (string)null);
                });

            modelBuilder.Entity("weightech_api.Models.FloorscaleTableModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Gate")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Net_lb")
                        .HasColumnType("REAL");

                    b.Property<long>("Serial")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServerGroup")
                        .HasColumnType("TEXT");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ServerGroup", "Gate", "Timestamp" }, "IX_floorscale_server_group_gate_timestamp")
                        .IsUnique();

                    b.HasIndex(new[] { "ServerGroup", "Timestamp" }, "IX_floorscale_server_group_timestamp");

                    b.HasIndex(new[] { "Timestamp" }, "index_floorscale_timestamp");

                    b.ToTable("floorscale", (string)null);
                });

            modelBuilder.Entity("weightech_api.Models.HopperTableModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Gate")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Net_lb")
                        .HasColumnType("REAL");

                    b.Property<long>("Serial")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServerGroup")
                        .HasColumnType("TEXT");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ServerGroup", "Gate", "Timestamp" }, "IX_hopper_server_group_gate_timestamp")
                        .IsUnique();

                    b.HasIndex(new[] { "Timestamp" }, "index_hopper_timestamp");

                    b.ToTable("hopper", (string)null);
                });

            modelBuilder.Entity("weightech_api.Models.SizerTableModel", b =>
                {
                    b.Property<long>("Gate")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Net_g")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Scale")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Serial")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServerGroup")
                        .HasColumnType("TEXT");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.HasIndex(new[] { "Scale", "Timestamp" }, "IX_sizer_scale_timestamp");

                    b.HasIndex(new[] { "Scale", "Gate", "Timestamp" }, "index_scale_gate_timestamp");

                    b.ToTable("sizer", (string)null);
                });

            modelBuilder.Entity("weightech_api.Models.StatusName", b =>
                {
                    b.Property<long?>("StatusIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("status_index");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("StatusIndex");

                    b.HasIndex(new[] { "StatusIndex", "Status" }, "IX_status_names_status_index_status")
                        .IsUnique();

                    b.ToTable("status_names", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
